name: Deploy react app using github actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: '0'
       token: ${{ github.token }}
    - name : git add notes
      run: |
        git config user.name "aashishverma-git"
        git config user.email "aashish23verma@gmail.com"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
       folder: build # The folder the action should deploy
